export interface ExerciseData {
  id?: string;
  name: string;
  category: string;
}

export const exercises: ExerciseData[] = [
  // Pecho
  { name: "Press de banca", category: "Pecho" },
  { name: "Press de banca inclinado", category: "Pecho" },
  { name: "Press de banca declinado", category: "Pecho" },
  { name: "Aperturas con mancuernas", category: "Pecho" },
  { name: "Aperturas inclinadas", category: "Pecho" },
  { name: "Aperturas en máquina", category: "Pecho" },
  { name: "Fondos en paralelas", category: "Pecho" },
  { name: "Press con mancuernas", category: "Pecho" },
  { name: "Press con mancuernas inclinado", category: "Pecho" },
  { name: "Pullover con mancuerna", category: "Pecho" },
  { name: "Crossover en polea alta", category: "Pecho" },
  { name: "Crossover en polea media", category: "Pecho" },
  { name: "Crossover en polea baja", category: "Pecho" },
  { name: "Press en máquina", category: "Pecho" },
  { name: "Press en máquina inclinado", category: "Pecho" },
  { name: "Press en máquina declinado", category: "Pecho" },
  { name: "Flexiones", category: "Pecho" },
  { name: "Flexiones inclinadas", category: "Pecho" },
  { name: "Flexiones declinadas", category: "Pecho" },
  { name: "Flexiones con aplauso", category: "Pecho" },

  // Espalda
  { name: "Dominadas", category: "Espalda" },
  { name: "Dominadas con agarre cerrado", category: "Espalda" },
  { name: "Dominadas con agarre abierto", category: "Espalda" },
  { name: "Jalón al pecho", category: "Espalda" },
  { name: "Jalón tras nuca", category: "Espalda" },
  { name: "Remo con barra", category: "Espalda" },
  { name: "Remo con mancuerna", category: "Espalda" },
  { name: "Remo en máquina", category: "Espalda" },
  { name: "Remo en polea baja", category: "Espalda" },
  { name: "Remo en T", category: "Espalda" },
  { name: "Peso muerto", category: "Espalda" },
  { name: "Peso muerto rumano", category: "Espalda" },
  { name: "Peso muerto sumo", category: "Espalda" },
  { name: "Pull-through en polea", category: "Espalda" },
  { name: "Hiperextensiones", category: "Espalda" },
  { name: "Good morning", category: "Espalda" },
  { name: "Face pull", category: "Espalda" },
  { name: "Pullover con polea", category: "Espalda" },
  { name: "Remo Meadows", category: "Espalda" },
  { name: "Remo Yates", category: "Espalda" },

  // Hombros
  { name: "Press militar", category: "Hombros" },
  { name: "Press militar con mancuernas", category: "Hombros" },
  { name: "Press Arnold", category: "Hombros" },
  { name: "Elevaciones laterales", category: "Hombros" },
  { name: "Elevaciones frontales", category: "Hombros" },
  { name: "Elevaciones posteriores", category: "Hombros" },
  { name: "Pájaros", category: "Hombros" },
  { name: "Remo al mentón", category: "Hombros" },
  { name: "Encogimientos de hombros", category: "Hombros" },
  { name: "Press en máquina", category: "Hombros" },
  { name: "Elevaciones laterales en polea", category: "Hombros" },
  { name: "Face pull", category: "Hombros" },
  { name: "Elevaciones 180°", category: "Hombros" },
  { name: "W press", category: "Hombros" },
  { name: "Pájaro en máquina", category: "Hombros" },
  { name: "Rotaciones externas", category: "Hombros" },
  { name: "Rotaciones internas", category: "Hombros" },
  { name: "Press Bradford", category: "Hombros" },
  { name: "Cuban press", category: "Hombros" },
  { name: "Landmine press", category: "Hombros" },

  // Bíceps
  { name: "Curl con barra", category: "Bíceps" },
  { name: "Curl con barra Z", category: "Bíceps" },
  { name: "Curl con mancuernas", category: "Bíceps" },
  { name: "Curl martillo", category: "Bíceps" },
  { name: "Curl concentrado", category: "Bíceps" },
  { name: "Curl Scott", category: "Bíceps" },
  { name: "Curl Scott con mancuernas", category: "Bíceps" },
  { name: "Curl en polea", category: "Bíceps" },
  { name: "Curl en polea con cuerda", category: "Bíceps" },
  { name: "Curl 21s", category: "Bíceps" },
  { name: "Curl araña", category: "Bíceps" },
  { name: "Curl de predicador", category: "Bíceps" },
  { name: "Curl Zottman", category: "Bíceps" },
  { name: "Curl inclinado", category: "Bíceps" },
  { name: "Curl en máquina", category: "Bíceps" },
  { name: "Curl inverso", category: "Bíceps" },
  { name: "Curl de muñeca", category: "Bíceps" },
  { name: "Dominadas supinas", category: "Bíceps" },
  { name: "Curl con polea alta", category: "Bíceps" },
  { name: "Curl alternado", category: "Bíceps" },

  // Tríceps
  { name: "Press francés", category: "Tríceps" },
  { name: "Press francés con mancuernas", category: "Tríceps" },
  { name: "Extensiones de tríceps en polea", category: "Tríceps" },
  { name: "Extensiones de tríceps con cuerda", category: "Tríceps" },
  { name: "Fondos en banco", category: "Tríceps" },
  { name: "Fondos en máquina", category: "Tríceps" },
  { name: "Patada de tríceps", category: "Tríceps" },
  { name: "Press cerrado", category: "Tríceps" },
  { name: "Extensiones sobre la cabeza", category: "Tríceps" },
  { name: "Extensiones con mancuerna", category: "Tríceps" },
  { name: "Extensiones en máquina", category: "Tríceps" },
  { name: "Rompecráneos", category: "Tríceps" },
  { name: "Extensiones tumbado", category: "Tríceps" },
  { name: "Fondos entre bancos", category: "Tríceps" },
  { name: "Extensiones en V", category: "Tríceps" },
  { name: "Press diamante", category: "Tríceps" },
  { name: "Extensiones con banda", category: "Tríceps" },
  { name: "Skull crusher", category: "Tríceps" },
  { name: "JM press", category: "Tríceps" },
  { name: "Dips", category: "Tríceps" },

  // Piernas
  { name: "Sentadillas", category: "Piernas" },
  { name: "Sentadillas frontales", category: "Piernas" },
  { name: "Sentadillas sumo", category: "Piernas" },
  { name: "Sentadillas búlgaras", category: "Piernas" },
  { name: "Prensa de piernas", category: "Piernas" },
  { name: "Extensiones de cuádriceps", category: "Piernas" },
  { name: "Curl femoral", category: "Piernas" },
  { name: "Curl femoral tumbado", category: "Piernas" },
  { name: "Curl femoral de pie", category: "Piernas" },
  { name: "Peso muerto", category: "Piernas" },
  { name: "Zancadas", category: "Piernas" },
  { name: "Zancadas laterales", category: "Piernas" },
  { name: "Sentadilla Hack", category: "Piernas" },
  { name: "Abductores", category: "Piernas" },
  { name: "Aductores", category: "Piernas" },
  { name: "Elevación de talones", category: "Piernas" },
  { name: "Elevación de talones sentado", category: "Piernas" },
  { name: "Sentadilla goblet", category: "Piernas" },
  { name: "Hip thrust", category: "Piernas" },
  { name: "Glute bridge", category: "Piernas" },
  { name: "Sentadilla sissy", category: "Piernas" },
  { name: "Extensión de cadera", category: "Piernas" },
  { name: "Patada de glúteo", category: "Piernas" },
  { name: "Sentadilla con salto", category: "Piernas" },
  { name: "Step-up", category: "Piernas" },
  { name: "Good morning", category: "Piernas" },
  { name: "Tijeras", category: "Piernas" },
  { name: "Sentadilla en máquina Smith", category: "Piernas" },
  { name: "Prensa vertical", category: "Piernas" },
  { name: "Sentadilla con barra por encima", category: "Piernas" },

  // Abdominales
  { name: "Crunch", category: "Abdominales" },
  { name: "Crunch con piernas elevadas", category: "Abdominales" },
  { name: "Crunch inverso", category: "Abdominales" },
  { name: "Elevaciones de piernas", category: "Abdominales" },
  { name: "Plancha", category: "Abdominales" },
  { name: "Plancha lateral", category: "Abdominales" },
  { name: "Russian twist", category: "Abdominales" },
  { name: "Mountain climber", category: "Abdominales" },
  { name: "Bicicleta", category: "Abdominales" },
  { name: "Hollow hold", category: "Abdominales" },
  { name: "Dragon flag", category: "Abdominales" },
  { name: "Rollout con rueda", category: "Abdominales" },
  { name: "Crunch en polea", category: "Abdominales" },
  { name: "Crunch en máquina", category: "Abdominales" },
  { name: "Elevaciones de piernas colgado", category: "Abdominales" },
  { name: "Windshield wiper", category: "Abdominales" },
  { name: "Toe touch", category: "Abdominales" },
  { name: "Scissors", category: "Abdominales" },
  { name: "Dead bug", category: "Abdominales" },
  { name: "Vacuum abdominal", category: "Abdominales" },

  // Cardio
  { name: "Carrera en cinta", category: "Cardio" },
  { name: "Bicicleta estática", category: "Cardio" },
  { name: "Elíptica", category: "Cardio" },
  { name: "Remo", category: "Cardio" },
  { name: "Salto a la comba", category: "Cardio" },
  { name: "Burpees", category: "Cardio" },
  { name: "Jumping jacks", category: "Cardio" },
  { name: "HIIT", category: "Cardio" },
  { name: "Escalador", category: "Cardio" },
  { name: "Spinning", category: "Cardio" },
  { name: "Natación", category: "Cardio" },
  { name: "Boxeo", category: "Cardio" },
  { name: "Kickboxing", category: "Cardio" },
  { name: "Zumba", category: "Cardio" },
  { name: "Aeróbic", category: "Cardio" },
  { name: "Step", category: "Cardio" },
  { name: "Carrera al aire libre", category: "Cardio" },
  { name: "Ciclismo", category: "Cardio" },
  { name: "Senderismo", category: "Cardio" },
  { name: "Escaleras", category: "Cardio" },

  // Estiramiento y Movilidad
  { name: "Estiramiento de cuádriceps", category: "Estiramiento" },
  { name: "Estiramiento de isquiotibiales", category: "Estiramiento" },
  { name: "Estiramiento de glúteos", category: "Estiramiento" },
  { name: "Estiramiento de aductores", category: "Estiramiento" },
  { name: "Estiramiento de pantorrillas", category: "Estiramiento" },
  { name: "Estiramiento de pecho", category: "Estiramiento" },
  { name: "Estiramiento de espalda", category: "Estiramiento" },
  { name: "Estiramiento de hombros", category: "Estiramiento" },
  { name: "Estiramiento de tríceps", category: "Estiramiento" },
  { name: "Estiramiento de bíceps", category: "Estiramiento" },
  { name: "Yoga", category: "Estiramiento" },
  { name: "Pilates", category: "Estiramiento" },
  { name: "Foam roller", category: "Estiramiento" },
  { name: "Movilidad de cadera", category: "Estiramiento" },
  { name: "Movilidad de hombros", category: "Estiramiento" },
  { name: "Movilidad de tobillos", category: "Estiramiento" },
  { name: "Movilidad de columna", category: "Estiramiento" },
  { name: "Movilidad de muñecas", category: "Estiramiento" },
  { name: "Child's pose", category: "Estiramiento" },
  { name: "Downward dog", category: "Estiramiento" },
];
